import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import AppArtwork from '@/components/AppArtwork';
import { getPublishedAppBySlug } from '@/lib/apps';
import { canonicalAppName, lifecycleLabel, solutionKindLabel } from '@/lib/application-presentation';

type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: Props): Promise<Metadata> { const app = await getPublishedAppBySlug((await params).slug); if (!app?.showInProjects) return { title: 'Case study not found', robots: { index: false, follow: false } }; const title = canonicalAppName(app.name); const description = (app.solutionSummary || app.description).slice(0, 155); const url = `/projects/${app.slug}`; return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: 'article' }, twitter: { card: 'summary_large_image', title, description } }; }

export default async function ProjectDetail({ params }: Props) {
  const app = await getPublishedAppBySlug((await params).slug); if (!app?.showInProjects) notFound(); const name = canonicalAppName(app.name);
  return <main className="min-h-screen bg-gray-50"><section className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-4xl px-4 sm:px-6"><Link href="/projects" className="font-semibold text-blue-300 hover:text-white">← Projects</Link><div className="mt-8 flex items-center gap-5"><AppArtwork app={app} variant="detail" className="h-24 w-24 shrink-0 rounded-2xl" /><div><p className="font-semibold text-blue-300">{solutionKindLabel(app.solutionKind)} · {lifecycleLabel(app.lifecycle)}</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">{name}</h1></div></div><p className="mt-6 text-lg leading-8 text-slate-200">{app.solutionSummary || app.description}</p></div></section><article className="mx-auto max-w-4xl space-y-10 px-4 py-12 sm:px-6">{app.clientProblem && <Block title="Problem"><p>{app.clientProblem}</p></Block>}{app.responsibilities.length > 0 && <List title="Responsibilities" items={app.responsibilities} />}{app.features.length > 0 && <List title="Capabilities" items={app.features} />}{app.technologies.length > 0 && <List title="Technology and disciplines" items={app.technologies} />}{app.challenges.length > 0 && <List title="Engineering challenges" items={app.challenges} />}{app.outcomes.some((item) => item.evidenceNote) && <Block title="Verified outcomes"><div className="grid gap-4 sm:grid-cols-2">{app.outcomes.filter((item) => item.evidenceNote).map((item) => <div key={`${item.label}-${item.value}`} className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-600">{item.label}</p><p className="mt-1 text-xl font-bold text-gray-900">{item.value}</p><p className="mt-2 text-sm text-gray-600">{item.evidenceNote}</p></div>)}</div></Block>}{app.confidentialityNote && <Block title="Confidentiality"><p>{app.confidentialityNote}</p></Block>}</article></main>;
}
function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold text-gray-900">{title}</h2><div className="mt-4 leading-7 text-gray-700">{children}</div></section>; }
function List({ title, items }: { title: string; items: string[] }) { return <Block title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex gap-3"><span className="text-blue-700">✓</span>{item}</li>)}</ul></Block>; }
