import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPublishedAppBySlug } from '@/lib/apps';
import { canonicalAppName, lifecycleLabel, solutionKindLabel } from '@/lib/application-presentation';
type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: Props): Promise<Metadata> { const app = await getPublishedAppBySlug((await params).slug); if (!app?.showInProjects) return { title: 'Case study not found', robots: { index: false, follow: false } }; const name = canonicalAppName(app.name); return { title: `${name} Case Study`, description: (app.solutionSummary || app.description).slice(0, 155), alternates: { canonical: `/projects/${app.slug}` } }; }
export default async function ProjectDetail({ params }: Props) { const app = await getPublishedAppBySlug((await params).slug); if (!app?.showInProjects) notFound(); const name = canonicalAppName(app.name); return <main className="min-h-screen bg-gray-50"><section className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-4xl px-4 sm:px-6"><Link href="/projects" className="font-semibold text-blue-300">← Projects</Link><p className="mt-8 font-semibold text-blue-300">{solutionKindLabel(app.solutionKind)} · {lifecycleLabel(app.status)}</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">{name}</h1><p className="mt-6 text-lg leading-8 text-slate-200">{app.solutionSummary || app.description}</p></div></section><article className="mx-auto max-w-4xl space-y-10 px-4 py-12 sm:px-6">{app.clientProblem && <Block title="Problem"><p>{app.clientProblem}</p></Block>}{app.responsibilities.length > 0 && <List title="Responsibilities" items={app.responsibilities} />}{app.features.length > 0 && <List title="Capabilities" items={app.features} />}{app.technologies.length > 0 && <List title="Technology and disciplines" items={app.technologies} />}{app.challenges.length > 0 && <List title="Engineering challenges" items={app.challenges} />}{app.outcomes.length > 0 && <Block title="Verified outcomes"><div className="grid gap-4 sm:grid-cols-2">{app.outcomes.map((item) => <div key={`${item.label}-${item.value}`} className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-600">{item.label}</p><p className="mt-1 text-xl font-bold text-gray-900">{item.value}</p>{item.evidenceNote && <p className="mt-2 text-sm text-gray-600">{item.evidenceNote}</p>}</div>)}</div></Block>}{app.confidentialityNote && <Block title="Confidentiality"><p>{app.confidentialityNote}</p></Block>}</article></main>; }
function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold text-gray-900">{title}</h2><div className="mt-4 leading-8 text-gray-700">{children}</div></section>; }
function List({ title, items }: { title: string; items: string[] }) { return <Block title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex gap-3"><span className="text-blue-700">✓</span>{item}</li>)}</ul></Block>; }
