import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPublishedAppBySlug } from '@/lib/apps';
import { approvedUpworkUrl, toUpworkSafeProject } from '@/lib/upwork-safe';
type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: Props): Promise<Metadata> { const app = await getPublishedAppBySlug((await params).slug); const project = app ? toUpworkSafeProject(app) : null; if (!project) return { title: 'Case study not found', robots: { index: false, follow: false } }; return { title: project.name, description: project.summary.slice(0, 155), alternates: { canonical: `/upwork-portfolio/${project.slug}` }, robots: { index: false, follow: true }, twitter: { card: 'summary_large_image', title: project.name, description: project.summary.slice(0, 155) } }; }
export default async function SafeProjectPage({ params }: Props) { const app = await getPublishedAppBySlug((await params).slug); const project = app ? toUpworkSafeProject(app) : null; if (!project) notFound(); const profile = approvedUpworkUrl(); return <main className="min-h-screen bg-slate-50"><section className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-4xl px-4 sm:px-6"><Link href="/upwork-portfolio" className="font-semibold text-blue-300 hover:text-white">← Professional portfolio</Link><p className="mt-8 font-semibold text-blue-300">{project.kind} · {project.lifecycle}</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">{project.name}</h1><p className="mt-6 text-lg leading-8 text-slate-200">{project.summary}</p></div></section><article className="mx-auto max-w-4xl space-y-10 px-4 py-12 sm:px-6">{project.responsibilities.length > 0 && <SafeList title="Responsibilities" items={project.responsibilities} />}{project.features.length > 0 && <SafeList title="Capabilities delivered" items={project.features} />}{project.technologies.length > 0 && <SafeList title="Technologies and disciplines" items={project.technologies} tags />}<section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-blue-950">Upwork communication notice</h2><p className="mt-2 text-blue-900">For Upwork opportunities, please continue all pre-contract communication and contracting through Upwork.</p>{profile && <a href={profile} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex rounded-lg bg-blue-700 px-4 py-2.5 font-bold text-white">Return to Upwork profile</a>}</section></article></main>; }
function SafeList({ title, items, tags = false }: { title: string; items: string[]; tags?: boolean }) { return <section><h2 className="text-2xl font-bold text-gray-900">{title}</h2>{tags ? <div className="mt-4 flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full bg-blue-100 px-3 py-1.5 text-sm font-semibold text-blue-900">{item}</span>)}</div> : <ul className="mt-4 space-y-3">{items.map((item) => <li key={item} className="flex gap-3 text-gray-700"><span className="text-blue-700">✓</span>{item}</li>)}</ul>}</section>; }
