import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import AppArtwork from '@/components/AppArtwork';
import { getPublishedAppBySlug } from '@/lib/apps';
import { approvedUpworkUrl, toUpworkSafeProject } from '@/lib/upwork-safe';

type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: Props): Promise<Metadata> { const app = await getPublishedAppBySlug((await params).slug); const project = app ? toUpworkSafeProject(app) : null; if (!project) return { title: 'Case study not found', robots: { index: false, follow: false } }; const description = project.summary.slice(0, 155); const url = `/upwork-portfolio/${project.slug}`; return { title: project.name, description, alternates: { canonical: url }, robots: { index: false, follow: true }, openGraph: { title: project.name, description, url, type: 'article' }, twitter: { card: 'summary_large_image', title: project.name, description } }; }

export default async function SafeProjectPage({ params }: Props) {
  const app = await getPublishedAppBySlug((await params).slug); const project = app ? toUpworkSafeProject(app) : null; if (!project || !app) notFound(); const profile = approvedUpworkUrl();
  return <main className="min-h-screen bg-slate-50"><section className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-4xl px-4 sm:px-6"><Link href="/upwork-portfolio" className="font-semibold text-blue-300 hover:text-white">← Professional portfolio</Link><div className="mt-8 flex items-center gap-5"><AppArtwork app={app} variant="detail" className="h-24 w-24 shrink-0 rounded-2xl" /><div><p className="font-semibold text-blue-300">{project.kind} · {project.lifecycle}</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">{project.name}</h1></div></div><p className="mt-6 text-lg leading-8 text-slate-200">{project.summary}</p></div></section><article className="mx-auto max-w-4xl space-y-10 px-4 py-12 sm:px-6">{project.problem && <TextBlock title="Problem">{project.problem}</TextBlock>}{project.role.length > 0 && <SafeList title="My role and responsibilities" items={project.role} />}{project.features.length > 0 && <SafeList title="Capabilities delivered" items={project.features} />}{project.technologies.length > 0 && <SafeList title="Technologies and disciplines" items={project.technologies} tags />}{project.skillTags.length > 0 && <SafeList title="Relevant Upwork skills" items={project.skillTags} tags />}{project.relevance && <TextBlock title="Why this is relevant">{project.relevance}</TextBlock>}{project.outcomes.length > 0 && <section><h2 className="text-2xl font-bold text-gray-900">Evidence-backed outcomes</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{project.outcomes.map((item) => <div key={`${item.label}-${item.value}`} className="rounded-xl border border-gray-200 bg-white p-5"><p className="text-sm font-semibold text-gray-600">{item.label}</p><p className="mt-1 text-xl font-bold text-gray-900">{item.value}</p><p className="mt-2 text-sm text-gray-600">{item.evidenceNote}</p></div>)}</div></section>}<section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-blue-950">Upwork communication notice</h2><p className="mt-2 text-blue-900">For Upwork opportunities, please continue all pre-contract communication, contracting, and payment through Upwork.</p>{profile && <a href={profile} target="_blank" rel="noopener noreferrer" aria-label="Return to Upwork profile (opens in a new tab)" className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-blue-700 px-4 py-2.5 font-bold text-white">Return to Upwork profile</a>}</section></article></main>;
}
function TextBlock({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold text-gray-900">{title}</h2><p className="mt-4 leading-7 text-gray-700">{children}</p></section>; }
function SafeList({ title, items, tags = false }: { title: string; items: string[]; tags?: boolean }) { return <section><h2 className="text-2xl font-bold text-gray-900">{title}</h2>{tags ? <div className="mt-4 flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full bg-blue-100 px-3 py-1.5 text-sm font-semibold text-blue-900">{item}</span>)}</div> : <ul className="mt-4 space-y-3">{items.map((item) => <li key={item} className="flex gap-3 text-gray-700"><span className="text-blue-700">✓</span>{item}</li>)}</ul>}</section>; }
