import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import AppArtwork from '@/components/AppArtwork';
import { getPublishedAppBySlug } from '@/lib/apps';
import { availabilityLabel, canonicalAppName, isCommercialProduct, lifecycleLabel, primaryCta, releaseArtifactReady, solutionKindLabel } from '@/lib/application-presentation';

type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const app = await getPublishedAppBySlug((await params).slug);
  if (!app) return { title: 'Solution not found', robots: { index: false, follow: false } };
  const name = canonicalAppName(app.name); const description = app.description.slice(0, 155); const image = app.thumbnailUrl || app.iconUrl;
  return { title: name, description, alternates: { canonical: `/app-store/${app.slug}` }, openGraph: { title: `${name} | Frontier DevConsults`, description, url: `/app-store/${app.slug}`, images: image ? [{ url: image, alt: `${name} artwork` }] : ['/og-image.png'] }, twitter: { card: 'summary_large_image', title: `${name} | Frontier DevConsults`, description, images: image ? [image] : ['/og-image.png'] } };
}

export default async function AppDetailPage({ params }: Props) {
  const app = await getPublishedAppBySlug((await params).slug); if (!app) notFound();
  const name = canonicalAppName(app.name); const cta = primaryCta(app, 'detail'); const releaseReady = releaseArtifactReady(app);
  const schema = { '@context': 'https://schema.org', '@type': app.solutionKind === 'website' || app.solutionKind === 'engineering_service' ? 'Service' : 'SoftwareApplication', name, description: app.description, applicationCategory: solutionKindLabel(app.solutionKind), operatingSystem: releaseReady ? app.artifactPlatform : undefined, url: `https://www.frontier-devconsults.com/app-store/${app.slug}` };
  const breadcrumbs = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Apps & Solutions', item: 'https://www.frontier-devconsults.com/app-store' }, { '@type': 'ListItem', position: 2, name, item: `https://www.frontier-devconsults.com/app-store/${app.slug}` }] };
  return <main id="main-content" className="min-h-screen bg-gray-50">
    <JsonLd value={schema} /><JsonLd value={breadcrumbs} />
    <section className="bg-gradient-to-br from-slate-950 to-blue-900 py-16 text-white"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><Link href="/app-store" className="text-sm font-semibold text-blue-200 hover:text-white">← Apps &amp; Solutions</Link><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-center"><AppArtwork name={name} src={app.thumbnailUrl || app.iconUrl} size="detail" priority /><div><p className="font-semibold text-blue-200">{solutionKindLabel(app.solutionKind)} · {app.category}</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">{name}</h1><div className="mt-4 flex flex-wrap gap-2"><Tag>{lifecycleLabel(app.lifecycle)}</Tag><Tag>{availabilityLabel(app.availability)}</Tag></div></div></div></div></section>
    <div className="mx-auto grid max-w-5xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_18rem] lg:px-8"><article className="space-y-10"><Section title="About this solution"><p className="whitespace-pre-line text-lg leading-8 text-gray-700">{app.description}</p></Section>{app.clientProblem && <Section title="Problem"><p>{app.clientProblem}</p></Section>}{app.solutionSummary && <Section title="Solution"><p>{app.solutionSummary}</p></Section>}{app.features.length > 0 && <ListSection title="Key capabilities" items={app.features} />}{app.responsibilities.length > 0 && <ListSection title="Responsibilities" items={app.responsibilities} />}{app.technologies.length > 0 && <ListSection title="Technology" items={app.technologies} tags />}{app.challenges.length > 0 && <ListSection title="Engineering challenges" items={app.challenges} />}{app.outcomes.length > 0 && <Section title="Verified outcomes"><dl className="grid gap-4 sm:grid-cols-2">{app.outcomes.map((outcome) => <div key={`${outcome.label}-${outcome.value}`} className="rounded-xl bg-gray-50 p-4"><dt className="font-semibold text-gray-700">{outcome.label}</dt><dd className="mt-1 text-xl font-bold text-gray-900">{outcome.value}</dd>{outcome.evidenceNote && <dd className="mt-2 text-sm text-gray-600">{outcome.evidenceNote}</dd>}</div>)}</dl></Section>}{app.confidentialityNote && <Section title="Confidentiality"><p>{app.confidentialityNote}</p></Section>}</article>
      <aside className="h-fit rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Current status</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Lifecycle" value={lifecycleLabel(app.lifecycle)} /><Row label="Availability" value={availabilityLabel(app.availability)} />{releaseReady && app.artifactVersion && <Row label="Version" value={app.artifactVersion} />}{releaseReady && app.artifactPlatform && <Row label="Platform" value={app.artifactPlatform} />}{releaseReady && app.artifactByteSize && <Row label="File size" value={formatBytes(app.artifactByteSize)} />}</dl>{app.artifactAvailability === 'temporarily_unavailable' && app.downloadLink && <p className="mt-5 rounded-lg bg-amber-50 p-3 text-sm font-semibold leading-5 text-amber-900">Download temporarily unavailable while release metadata is being verified.</p>}{isCommercialProduct(app) && <div className="mt-6 border-t border-gray-200 pt-5"><h3 className="font-bold text-gray-900">Commercial options</h3><ul className="mt-2 space-y-1 text-sm capitalize text-gray-700">{app.commercialModes.map((mode) => <li key={mode}>{mode.replaceAll('_', ' ')}</li>)}</ul><p className="mt-3 font-semibold">Commercial terms by enquiry</p></div>}{cta && <div className="mt-6">{cta.external ? <a href={cta.href} target="_blank" rel="noopener noreferrer" aria-label={`${cta.label} for ${name} (opens in a new tab)`} className="block rounded-lg bg-blue-600 px-4 py-3 text-center font-semibold text-white hover:bg-blue-700">{cta.label}</a> : <Link href={cta.href} className="block rounded-lg bg-blue-600 px-4 py-3 text-center font-semibold text-white hover:bg-blue-700">{cta.label}</Link>}</div>}<p className="mt-5 text-xs leading-5 text-gray-500">Licensing, acquisition, support and customization are subject to an owner-approved written quotation and terms. No transaction is completed on this page.</p></aside></div>
  </main>;
}

function JsonLd({ value }: { value: object }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(value).replaceAll('<', '\\u003c') }} />; }
function formatBytes(value: number) { const units = ['B', 'KB', 'MB', 'GB']; let amount = value; let unit = 0; while (amount >= 1024 && unit < units.length - 1) { amount /= 1024; unit += 1; } return `${amount.toFixed(unit === 0 ? 0 : 1)} ${units[unit]}`; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-4 text-2xl font-bold text-gray-900">{title}</h2><div className="leading-7 text-gray-700">{children}</div></section>; }
function ListSection({ title, items, tags = false }: { title: string; items: string[]; tags?: boolean }) { return <Section title={title}>{tags ? <div className="flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-semibold text-blue-800">{item}</span>)}</div> : <ul className="space-y-2">{items.map((item) => <li key={item} className="flex gap-2"><span className="text-blue-600">✓</span>{item}</li>)}</ul>}</Section>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-white/15 px-3 py-1 text-sm font-bold text-white">{children}</span>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3"><dt className="text-gray-500">{label}</dt><dd className="text-right font-semibold text-gray-900">{value}</dd></div>; }
