'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ExternalLink, LoaderCircle, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { acquisitionStatuses, labels } from '@/lib/acquisition-options';

type RequestRecord = {
  id: string; reference_number: string; product_slug: string; product_name: string; buyer_full_name: string; buyer_company: string; buyer_email: string;
  buyer_phone: string | null; buyer_country: string; buyer_website: string | null; buyer_role: string | null; buyer_type: string; acquisition_type: string;
  intended_use: string; deployment_market: string; source_code_transfer: string; ip_branding_transfer: string; completion_requirement: string;
  additional_development_requirements: string | null; support_requirement: string; budget_range: string | null; acquisition_timeline: string;
  additional_requirements: string | null; status: string; internal_notes: string; assigned_follow_up: string | null; buyer_qualification: string;
  nda_status: string; demo_status: string; negotiation_status: string; utm_source: string | null; utm_medium: string | null; utm_campaign: string | null;
  referrer: string | null; landing_page: string | null; created_at: string; updated_at: string;
};

const qualificationOptions = ['not_reviewed', 'qualified', 'needs_information', 'not_qualified'];
const ndaOptions = ['not_required', 'required', 'sent', 'signed'];
const demoOptions = ['not_scheduled', 'requested', 'scheduled', 'completed'];
const negotiationOptions = ['not_started', 'preliminary', 'active', 'paused', 'agreed', 'unsuccessful'];
const titleCase = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const formatDate = (value: string) => new Intl.DateTimeFormat('en-GH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export default function AcquisitionRequestsPage() {
  const [requests, setRequests] = useState<RequestRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [product, setProduct] = useState('all'); const [country, setCountry] = useState('all'); const [type, setType] = useState('all'); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const [saving, setSaving] = useState<string | null>(null); const [notes, setNotes] = useState<Record<string, string>>({});
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch('/api/admin/acquisitions', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Unable to load acquisition requests.'); setRequests(payload); setNotes(Object.fromEntries(payload.map((item: RequestRecord) => [item.id, item.internal_notes || '']))); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load acquisition requests.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const products = useMemo(() => Array.from(new Set(requests.map((item) => item.product_slug))).sort(), [requests]);
  const countries = useMemo(() => Array.from(new Set(requests.map((item) => item.buyer_country))).sort(), [requests]);
  const types = useMemo(() => Array.from(new Set(requests.map((item) => item.acquisition_type))).sort(), [requests]);
  const visible = useMemo(() => { const needle = search.trim().toLowerCase(); return requests.filter((item) => { const created = new Date(item.created_at).getTime(); const afterStart = !fromDate || created >= new Date(`${fromDate}T00:00:00`).getTime(); const beforeEnd = !toDate || created <= new Date(`${toDate}T23:59:59.999`).getTime(); return (status === 'all' || item.status === status) && (product === 'all' || item.product_slug === product) && (country === 'all' || item.buyer_country === country) && (type === 'all' || item.acquisition_type === type) && afterStart && beforeEnd && (!needle || [item.reference_number, item.product_name, item.buyer_full_name, item.buyer_company, item.buyer_email].some((value) => value.toLowerCase().includes(needle))); }); }, [requests, search, status, product, country, type, fromDate, toDate]);

  async function update(item: RequestRecord, changes: Record<string, string>, key: string) { setSaving(`${item.id}-${key}`); setError(''); try { const response = await fetch(`/api/admin/acquisitions/${item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Unable to update acquisition request.'); setRequests((current) => current.map((request) => request.id === item.id ? payload : request)); setNotes((current) => ({ ...current, [item.id]: payload.internal_notes || '' })); } catch (updateError) { setError(updateError instanceof Error ? updateError.message : 'Unable to update acquisition request.'); } finally { setSaving(null); } }

  return <main className="min-h-screen bg-gray-50"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/admin/dashboard" className="mb-4 inline-flex items-center gap-2 text-blue-600 hover:text-blue-700"><ArrowLeft className="h-4 w-4" />Back to Dashboard</Link><h1 className="text-3xl font-bold text-gray-950">Application Acquisition Requests</h1><p className="mt-2 text-gray-600">Review buyer requirements and manage qualification, NDA, demonstration, negotiation, completion, and handover stages.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2 font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>
    <div className="mb-6 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><label className="relative"><span className="sr-only">Search requests</span><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search buyer or reference" className="w-full rounded-lg border border-gray-300 py-2 pl-9 pr-3" /></label><Filter label="Status" value={status} setValue={setStatus} options={acquisitionStatuses.map(String)} labelsMap={labels.status as Record<string, string>} /><Filter label="Product" value={product} setValue={setProduct} options={products} /><Filter label="Country" value={country} setValue={setCountry} options={countries} /><Filter label="Acquisition type" value={type} setValue={setType} options={types} labelsMap={labels.acquisitionType as Record<string, string>} /><DateFilter label="From date" value={fromDate} setValue={setFromDate} /><DateFilter label="To date" value={toDate} setValue={setToDate} /><button type="button" onClick={() => { setSearch(''); setStatus('all'); setProduct('all'); setCountry('all'); setType('all'); setFromDate(''); setToDate(''); }} className="rounded-lg border border-gray-300 px-3 py-2 font-semibold text-gray-700">Reset filters</button></div>
    {error && <div role="alert" className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    {loading ? <div className="flex min-h-72 items-center justify-center gap-2 text-gray-600"><LoaderCircle className="h-5 w-5 animate-spin" />Loading acquisition requests...</div> : visible.length === 0 ? <div className="rounded-xl border border-dashed border-gray-300 bg-white py-16 text-center"><ShieldCheck className="mx-auto h-12 w-12 text-gray-300" /><h2 className="mt-4 text-xl font-bold text-gray-900">No matching acquisition requests</h2></div> : <div className="space-y-5">{visible.map((item) => <article key={item.id} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge>{labels.status[item.status as keyof typeof labels.status] || titleCase(item.status)}</Badge><Badge green>{labels.acquisitionType[item.acquisition_type as keyof typeof labels.acquisitionType] || titleCase(item.acquisition_type)}</Badge></div><h2 className="mt-3 text-xl font-bold text-gray-950">{item.product_name} — {item.buyer_company}</h2><p className="mt-1 font-mono text-sm font-semibold text-gray-600">{item.reference_number}</p><p className="mt-2 text-sm text-gray-500">Received {formatDate(item.created_at)}</p></div><label className="min-w-64 text-sm font-semibold text-gray-700">Workflow status<select value={item.status} onChange={(event) => void update(item, { status: event.target.value }, 'status')} disabled={saving === `${item.id}-status`} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2">{acquisitionStatuses.map((value) => <option key={value} value={value}>{labels.status[value]}</option>)}</select></label></div>
      <details className="mt-5 border-t border-gray-200 pt-5"><summary className="cursor-pointer font-bold text-blue-700">Review complete request</summary><div className="mt-5 space-y-6"><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Data label="Buyer" value={`${item.buyer_full_name}${item.buyer_role ? ` — ${item.buyer_role}` : ''}`} /><Data label="Email" value={item.buyer_email} /><Data label="Phone" value={item.buyer_phone || 'Not provided'} /><Data label="Country" value={item.buyer_country} /><Data label="Buyer type" value={titleCase(item.buyer_type)} /><Data label="Market" value={item.deployment_market} /><Data label="Budget" value={item.budget_range ? (labels.budget[item.budget_range as keyof typeof labels.budget] || titleCase(item.budget_range)) : 'Not disclosed'} /><Data label="Timeline" value={labels.timeline[item.acquisition_timeline as keyof typeof labels.timeline] || titleCase(item.acquisition_timeline)} /></dl>
        <TextBlock title="Intended use" value={item.intended_use} /><div className="grid gap-4 text-sm sm:grid-cols-2"><Data label="Source-code transfer" value={titleCase(item.source_code_transfer)} /><Data label="IP / branding transfer" value={titleCase(item.ip_branding_transfer)} /><Data label="Completion requirement" value={titleCase(item.completion_requirement)} /><Data label="Support requirement" value={titleCase(item.support_requirement)} /></div>{item.additional_development_requirements && <TextBlock title="Additional development" value={item.additional_development_requirements} />}{item.additional_requirements && <TextBlock title="Additional requirements" value={item.additional_requirements} />}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><WorkflowSelect label="Buyer qualification" value={item.buyer_qualification} options={qualificationOptions} onChange={(value) => void update(item, { buyerQualification: value }, 'qualification')} /><WorkflowSelect label="NDA" value={item.nda_status} options={ndaOptions} onChange={(value) => void update(item, { ndaStatus: value }, 'nda')} /><WorkflowSelect label="Private demo" value={item.demo_status} options={demoOptions} onChange={(value) => void update(item, { demoStatus: value }, 'demo')} /><WorkflowSelect label="Negotiation" value={item.negotiation_status} options={negotiationOptions} onChange={(value) => void update(item, { negotiationStatus: value }, 'negotiation')} /></div>
        <label className="block text-sm font-semibold text-gray-700">Assigned follow-up<input defaultValue={item.assigned_follow_up || ''} onBlur={(event) => { if (event.target.value !== (item.assigned_follow_up || '')) void update(item, { assignedFollowUp: event.target.value }, 'assignee'); }} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="block text-sm font-semibold text-gray-700">Private internal notes<textarea value={notes[item.id] || ''} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} rows={5} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><button type="button" onClick={() => void update(item, { internalNotes: notes[item.id] || '' }, 'notes')} disabled={saving === `${item.id}-notes`} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-60">{saving === `${item.id}-notes` ? 'Saving...' : 'Save internal notes'}</button>
        {(item.buyer_website || item.landing_page || item.referrer) && <div className="rounded-lg bg-gray-50 p-4 text-sm"><h3 className="font-bold text-gray-900">Links and attribution</h3>{item.buyer_website && <a href={item.buyer_website} target="_blank" rel="noopener noreferrer" className="mt-2 flex items-center gap-1 text-blue-700">Buyer website <ExternalLink className="h-3 w-3" /></a>}<p className="mt-2 break-all text-gray-600">Campaign: {[item.utm_source, item.utm_medium, item.utm_campaign].filter(Boolean).join(' / ') || 'Direct or unavailable'}</p></div>}
      </div></details></article>)}</div>}
  </div></main>;
}

function Filter({ label, value, setValue, options, labelsMap }: { label: string; value: string; setValue: (value: string) => void; options: string[]; labelsMap?: Record<string, string> }) { return <label><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(event) => setValue(event.target.value)} className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2"><option value="all">All {label.toLowerCase()}s</option>{options.map((option) => <option key={option} value={option}>{labelsMap?.[option] || titleCase(option)}</option>)}</select></label>; }
function DateFilter({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <label className="text-xs font-semibold text-gray-600">{label}<input aria-label={label} type="date" value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-normal text-gray-900" /></label>; }
function Badge({ children, green = false }: { children: React.ReactNode; green?: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${green ? 'bg-emerald-50 text-emerald-800' : 'bg-blue-50 text-blue-800'}`}>{children}</span>; }
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="font-semibold text-gray-500">{label}</dt><dd className="mt-1 break-words text-gray-900">{value}</dd></div>; }
function TextBlock({ title, value }: { title: string; value: string }) { return <div><h3 className="text-sm font-bold text-gray-900">{title}</h3><p className="mt-1 whitespace-pre-wrap rounded-lg bg-gray-50 p-4 text-sm leading-6 text-gray-700">{value}</p></div>; }
function WorkflowSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-gray-700">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2">{options.map((option) => <option key={option} value={option}>{titleCase(option)}</option>)}</select></label>; }
