'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { FormEvent, type InputHTMLAttributes, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, LoaderCircle } from 'lucide-react';
import { acquisitionTimelines, allowedAcquisitionTypes, budgetRanges, buyerTypes, completionRequirements, labels, supportRequirements, transferChoices } from '@/lib/acquisition-options';
import type { AppRecord } from '@/lib/apps';
import { recordCommercialEvent } from '@/components/CommercialEvent';

type FormState = {
  fullName: string; company: string; email: string; phone: string; country: string; website: string; role: string; buyerType: string;
  acquisitionType: string; intendedUse: string; deploymentMarket: string; sourceCodeTransfer: string; ipBrandingTransfer: string;
  completionRequirement: string; additionalDevelopmentRequirements: string; supportRequirement: string; budgetRange: string;
  acquisitionTimeline: string; additionalRequirements: string; legalAcknowledged: boolean; privacyAcknowledged: boolean; websiteField: string;
};

const initial: FormState = { fullName: '', company: '', email: '', phone: '', country: '', website: '', role: '', buyerType: '', acquisitionType: '', intendedUse: '', deploymentMarket: '', sourceCodeTransfer: '', ipBrandingTransfer: '', completionRequirement: '', additionalDevelopmentRequirements: '', supportRequirement: '', budgetRange: '', acquisitionTimeline: '', additionalRequirements: '', legalAcknowledged: false, privacyAcknowledged: false, websiteField: '' };
const stepNames = ['Buyer Information', 'Acquisition Type', 'Technical Requirements', 'Development & Support', 'Budget & Timeline', 'Review & Submit'];

export default function AcquisitionForm({ app }: { app: AppRecord }) {
  const router = useRouter(); const searchParams = useSearchParams();
  const [step, setStep] = useState(0); const [form, setForm] = useState(initial); const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false); const [submissionError, setSubmissionError] = useState('');
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  const availableTypes = useMemo(() => allowedAcquisitionTypes(app), [app]);
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => { const next = { ...current }; delete next[key]; return next; }); };

  function validateStep(index: number) {
    const next: Record<string, string> = {};
    const need = (key: keyof FormState, label: string) => { if (!String(form[key]).trim()) next[key] = `${label} is required.`; };
    if (index === 0) { need('fullName', 'Full name'); need('company', 'Company or organization'); need('email', 'Email address'); need('country', 'Country'); need('buyerType', 'Buyer type'); if (form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (form.website) { try { const url = new URL(form.website); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); } catch { next.website = 'Enter a valid website beginning with http:// or https://.'; } } }
    if (index === 1) { need('acquisitionType', 'Acquisition type'); need('intendedUse', 'Intended use'); need('deploymentMarket', 'Deployment market'); }
    if (index === 2) { need('sourceCodeTransfer', 'Source-code preference'); need('ipBrandingTransfer', 'IP and branding preference'); }
    if (index === 3) { need('completionRequirement', 'Development-completion preference'); need('supportRequirement', 'Support preference'); }
    if (index === 4) need('acquisitionTimeline', 'Acquisition timeline');
    if (index === 5) { if (!form.legalAcknowledged) next.legalAcknowledged = 'The legal acknowledgment is required.'; if (!form.privacyAcknowledged) next.privacyAcknowledged = 'The privacy acknowledgment is required.'; }
    setErrors(next); return Object.keys(next).length === 0;
  }
  function nextStep() { if (!validateStep(step)) return; const next = Math.min(step + 1, stepNames.length - 1); if (step === 0) recordCommercialEvent('acquisition_form_started', app.slug || undefined); setStep(next); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function previousStep() { setStep((current) => Math.max(0, current - 1)); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!validateStep(5) || !app.slug) return;
    setSubmitting(true); setSubmissionError(''); recordCommercialEvent('acquisition_form_completed', app.slug);
    const query = new URLSearchParams(searchParams.toString());
    try {
      const response = await fetch('/api/acquisitions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, productSlug: app.slug, idempotencyKey, attribution: { utmSource: query.get('utm_source'), utmMedium: query.get('utm_medium'), utmCampaign: query.get('utm_campaign'), utmContent: query.get('utm_content'), utmTerm: query.get('utm_term'), referrer: document.referrer, landingPage: window.location.href } }) });
      const payload = await response.json();
      if (!response.ok) { if (payload.fields) setErrors(payload.fields); throw new Error(payload.error || 'Unable to submit the request.'); }
      recordCommercialEvent('acquisition_request_submitted', app.slug); router.push(`/acquisition/confirmation/${encodeURIComponent(payload.reference)}`);
    } catch (error) { setSubmissionError(error instanceof Error ? error.message : 'Unable to submit the request.'); }
    finally { setSubmitting(false); }
  }

  return <form onSubmit={submit} noValidate className="rounded-2xl border border-gray-200 bg-white shadow-xl">
    <div className="border-b border-gray-200 p-5 sm:p-7"><p className="text-sm font-bold uppercase tracking-[0.18em] text-blue-700">Step {step + 1} of {stepNames.length}</p><h2 className="mt-2 text-2xl font-bold text-gray-950">{stepNames[step]}</h2><div className="mt-5 grid grid-cols-6 gap-2" aria-label="Acquisition form progress">{stepNames.map((name, index) => <div key={name} className={`h-2 rounded-full ${index <= step ? 'bg-blue-600' : 'bg-gray-200'}`} title={name} />)}</div></div>
    <div className="p-5 sm:p-8">
      {Object.keys(errors).length > 0 && <div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><p className="font-bold">Please correct the highlighted information.</p></div>}
      {submissionError && <div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{submissionError}</div>}
      {step === 0 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name" required error={errors.fullName}><Input value={form.fullName} onChange={(value) => update('fullName', value)} autoComplete="name" /></Field><Field label="Company / Organization" required error={errors.company}><Input value={form.company} onChange={(value) => update('company', value)} autoComplete="organization" /></Field><Field label="Email Address" required error={errors.email}><Input type="email" value={form.email} onChange={(value) => update('email', value)} autoComplete="email" /></Field><Field label="Country" required error={errors.country}><Input value={form.country} onChange={(value) => update('country', value)} autoComplete="country-name" /></Field><Field label="Phone Number"><Input type="tel" value={form.phone} onChange={(value) => update('phone', value)} autoComplete="tel" /></Field><Field label="Website" error={errors.website}><Input type="url" value={form.website} onChange={(value) => update('website', value)} placeholder="https://" /></Field><Field label="Job Title / Role"><Input value={form.role} onChange={(value) => update('role', value)} autoComplete="organization-title" /></Field><Field label="Buyer Type" required error={errors.buyerType}><Select value={form.buyerType} onChange={(value) => update('buyerType', value)} options={buyerTypes.map((value) => ({ value, label: labels.buyerType[value] }))} /></Field></div>}
      {step === 1 && <div className="space-y-6"><Field label="Acquisition Type" required error={errors.acquisitionType}><Select value={form.acquisitionType} onChange={(value) => update('acquisitionType', value)} options={availableTypes.map((value) => ({ value, label: labels.acquisitionType[value] }))} /></Field><Field label="Intended Use" required hint="Briefly describe how you intend to use or commercialize this application." error={errors.intendedUse}><Textarea value={form.intendedUse} onChange={(value) => update('intendedUse', value)} /></Field><Field label="Deployment Market / Region" required hint="Enter a country, region, multiple markets, global, or not yet decided." error={errors.deploymentMarket}><Input value={form.deploymentMarket} onChange={(value) => update('deploymentMarket', value)} /></Field></div>}
      {step === 2 && <div className="space-y-6"><Field label="Do you require source-code transfer?" required error={errors.sourceCodeTransfer}><ChoiceGroup name="sourceCodeTransfer" value={form.sourceCodeTransfer} onChange={(value) => update('sourceCodeTransfer', value)} options={transferChoices.map((value) => ({ value, label: labels.transfer[value] }))} /></Field><Field label="Are you interested in acquiring application branding and associated transferable intellectual-property rights where available?" required error={errors.ipBrandingTransfer}><ChoiceGroup name="ipBrandingTransfer" value={form.ipBrandingTransfer} onChange={(value) => update('ipBrandingTransfer', value)} options={transferChoices.map((value) => ({ value, label: labels.transfer[value] }))} /></Field><p className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">Trademarks, domains, third-party assets, provider accounts, and external licences are not automatically transferable. The precise scope is established during review and documented in the final agreement.</p></div>}
      {step === 3 && <div className="space-y-6"><Field label="Would you like Frontier DevConsults to complete remaining development before handover or deployment?" required error={errors.completionRequirement}><Select value={form.completionRequirement} onChange={(value) => update('completionRequirement', value)} options={completionRequirements.map((value) => ({ value, label: labels.completion[value] }))} /></Field>{['complete_before_handover', 'complete_to_requirements'].includes(form.completionRequirement) && <Field label="Additional Development Requirements"><Textarea value={form.additionalDevelopmentRequirements} onChange={(value) => update('additionalDevelopmentRequirements', value)} /></Field>}<Field label="Do you require ongoing Frontier DevConsults technical support after acquisition?" required error={errors.supportRequirement}><ChoiceGroup name="supportRequirement" value={form.supportRequirement} onChange={(value) => update('supportRequirement', value)} options={supportRequirements.map((value) => ({ value, label: labels.support[value] }))} /></Field></div>}
      {step === 4 && <div className="space-y-6"><Field label="Budget Range" hint="Optional"><Select value={form.budgetRange} onChange={(value) => update('budgetRange', value)} options={budgetRanges.map((value) => ({ value, label: labels.budget[value] }))} optionalLabel="Select a range or leave undisclosed" /></Field><Field label="Preferred Acquisition Timeline" required error={errors.acquisitionTimeline}><Select value={form.acquisitionTimeline} onChange={(value) => update('acquisitionTimeline', value)} options={acquisitionTimelines.map((value) => ({ value, label: labels.timeline[value] }))} /></Field><Field label="Additional Requirements / Questions"><Textarea value={form.additionalRequirements} onChange={(value) => update('additionalRequirements', value)} /></Field></div>}
      {step === 5 && <div className="space-y-6"><div className="rounded-xl bg-slate-50 p-5"><h3 className="font-bold text-gray-950">Request summary</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Summary label="Buyer" value={form.fullName} /><Summary label="Organization" value={form.company} /><Summary label="Application" value={app.name} /><Summary label="Request type" value={form.acquisitionType ? labels.acquisitionType[form.acquisitionType as keyof typeof labels.acquisitionType] : ''} /><Summary label="Market" value={form.deploymentMarket} /><Summary label="Timeline" value={form.acquisitionTimeline ? labels.timeline[form.acquisitionTimeline as keyof typeof labels.timeline] : ''} /></dl></div><CheckField checked={form.legalAcknowledged} onChange={(value) => update('legalAcknowledged', value)} error={errors.legalAcknowledged}>I understand that submitting this acquisition request initiates commercial discussions with Frontier DevConsults and does not constitute a purchase agreement, transfer of ownership, assignment of intellectual property, license grant, or binding commitment by either party.</CheckField><CheckField checked={form.privacyAcknowledged} onChange={(value) => update('privacyAcknowledged', value)} error={errors.privacyAcknowledged}>I agree that Frontier DevConsults may use the information provided to evaluate and respond to this commercial inquiry in accordance with its <Link href="/privacy" className="font-semibold text-blue-700 underline">Privacy Policy</Link>.</CheckField></div>}
      <div className="hidden" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={form.websiteField} onChange={(event) => update('websiteField', event.target.value)} /></label></div>
    </div>
    <div className="flex flex-col-reverse gap-3 border-t border-gray-200 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-7"><div>{step > 0 ? <button type="button" onClick={previousStep} className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-gray-300 px-5 py-3 font-semibold text-gray-700 hover:bg-gray-50 sm:w-auto"><ArrowLeft className="h-4 w-4" />Previous</button> : <Link href={`/app-store/${app.slug}`} className="inline-flex w-full items-center justify-center rounded-lg border border-gray-300 px-5 py-3 font-semibold text-gray-700 hover:bg-gray-50 sm:w-auto">Return to Product</Link>}</div>{step < stepNames.length - 1 ? <button type="button" onClick={nextStep} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-6 py-3 font-bold text-white hover:bg-blue-700 sm:w-auto">Continue<ArrowRight className="h-4 w-4" /></button> : <button type="submit" disabled={submitting} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-6 py-3 font-bold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto">{submitting ? <LoaderCircle className="h-5 w-5 animate-spin" /> : <Check className="h-5 w-5" />}{submitting ? 'Submitting securely...' : 'Initiate Application Acquisition'}</button>}</div>
  </form>;
}

function Field({ label, required, hint, error, children }: { label: string; required?: boolean; hint?: string; error?: string; children: React.ReactNode }) { return <label className="block font-semibold text-gray-800"><span>{label}{required && <span aria-hidden="true"> *</span>}</span>{hint && <span className="mt-1 block text-sm font-normal text-gray-500">{hint}</span>}<div className="mt-2">{children}</div>{error && <span className="mt-1 block text-sm font-medium text-red-700">{error}</span>}</label>; }
function Input({ value, onChange, type = 'text', ...props }: { value: string; onChange: (value: string) => void; type?: string } & Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange' | 'type'>) { return <input {...props} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-3 font-normal text-gray-950 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" />; }
function Textarea({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <textarea rows={5} maxLength={5000} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-3 font-normal text-gray-950 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" />; }
function Select({ value, onChange, options, optionalLabel = 'Select an option' }: { value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }>; optionalLabel?: string }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 font-normal text-gray-950 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100"><option value="">{optionalLabel}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>; }
function ChoiceGroup({ name, value, onChange, options }: { name: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <div className="grid gap-3 sm:grid-cols-3">{options.map((option) => <label key={option.value} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-4 font-medium ${value === option.value ? 'border-blue-600 bg-blue-50 text-blue-900' : 'border-gray-300'}`}><input type="radio" name={name} value={option.value} checked={value === option.value} onChange={() => onChange(option.value)} />{option.label}</label>)}</div>; }
function CheckField({ checked, onChange, error, children }: { checked: boolean; onChange: (value: boolean) => void; error?: string; children: React.ReactNode }) { return <div><label className={`flex items-start gap-3 rounded-xl border p-4 text-sm leading-6 ${error ? 'border-red-300 bg-red-50' : 'border-gray-300'}`}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-4 w-4 shrink-0" /><span>{children}</span></label>{error && <p className="mt-1 text-sm font-medium text-red-700">{error}</p>}</div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><dt className="text-gray-500">{label}</dt><dd className="mt-1 font-semibold text-gray-900">{value || 'Not provided'}</dd></div>; }
