'use client';

import Link from 'next/link';
import { ExternalLink, Search, Smartphone } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { AppRecord } from '@/lib/apps';
import { availabilityLabel, canonicalAppName, compactSummary, isCommercialProduct, lifecycleLabel, primaryCta, solutionKindLabel } from '@/lib/application-presentation';

export default function AppCatalogue({ apps }: { apps: AppRecord[] }) {
  const [search, setSearch] = useState(''); const [kind, setKind] = useState('all'); const [lifecycle, setLifecycle] = useState('all'); const [availability, setAvailability] = useState('all');
  const queryReady = useRef(false);
  useEffect(() => { const query = new URLSearchParams(window.location.search); setSearch(query.get('q') || ''); setKind(query.get('kind') || 'all'); setLifecycle(query.get('lifecycle') || 'all'); setAvailability(query.get('availability') || 'all'); queryReady.current = true; }, []);
  useEffect(() => { if (!queryReady.current) return; const url = new URL(window.location.href); const values = { q: search, kind, lifecycle, availability }; Object.entries(values).forEach(([key, value]) => value && value !== 'all' ? url.searchParams.set(key, value) : url.searchParams.delete(key)); window.history.replaceState(null, '', `${url.pathname}${url.search}${url.hash}`); }, [search, kind, lifecycle, availability]);
  const filtered = useMemo(() => apps.filter((app) => { const query = search.trim().toLowerCase(); return (!query || [app.name, app.category, app.description, ...app.features, ...app.technologies].join(' ').toLowerCase().includes(query)) && (kind === 'all' || app.solutionKind === kind) && (lifecycle === 'all' || app.status === lifecycle) && (availability === 'all' || app.availability === availability); }), [apps, search, kind, lifecycle, availability]);
  const reset = () => { setSearch(''); setKind('all'); setLifecycle('all'); setAvailability('all'); };
  return <><div className="mb-8 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="grid gap-4 lg:grid-cols-[2fr_1fr_1fr_1fr_auto]"><label className="relative"><span className="sr-only">Search solutions</span><Search className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search apps and solutions" className="w-full rounded-lg border border-gray-300 py-2.5 pl-10 pr-3" /></label><Filter label="Solution kind" value={kind} onChange={setKind} options={Array.from(new Set(apps.map((app) => app.solutionKind)))} formatter={solutionKindLabel} /><Filter label="Lifecycle" value={lifecycle} onChange={setLifecycle} options={['Published', 'Development', 'Planning']} formatter={(value) => value === 'Development' ? 'In Development' : value === 'Published' ? 'Live' : value} /><Filter label="Availability" value={availability} onChange={setAvailability} options={['available', 'coming_soon', 'by_enquiry', 'unavailable']} formatter={(value) => availabilityLabel(value as AppRecord['availability'])} /><button type="button" onClick={reset} className="rounded-lg border border-gray-300 px-4 py-2.5 font-semibold text-gray-700 hover:bg-gray-50">Reset</button></div><p className="mt-4 text-sm text-gray-600" aria-live="polite">{filtered.length} {filtered.length === 1 ? 'solution' : 'solutions'} found</p></div>{filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-gray-300 bg-white p-12 text-center"><h2 className="text-xl font-bold text-gray-900">No matching solutions</h2><p className="mt-2 text-gray-600">Try a broader search or reset the filters.</p></div> : <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map((app) => <AppCard key={app.id} app={app} />)}</div>}</>;
}

function Filter({ label, value, onChange, options, formatter }: { label: string; value: string; onChange: (value: string) => void; options: string[]; formatter: (value: any) => string }) { return <label><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-gray-300 px-3 py-2.5"><option value="all">All {label.toLowerCase()}s</option>{options.map((option) => <option key={option} value={option}>{formatter(option)}</option>)}</select></label>; }

export function AppCard({ app }: { app: AppRecord }) {
  const cta = primaryCta(app); const name = canonicalAppName(app.name);
  return <article className="flex h-full flex-col rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex gap-4">{app.iconUrl ? <img src={app.iconUrl} alt={`${name} icon`} loading="lazy" className="h-16 w-16 shrink-0 rounded-xl border border-gray-100 bg-gray-50 object-contain p-1" /> : <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-100 to-purple-100 text-blue-700" aria-label={`${name} has no uploaded artwork`}><Smartphone className="h-8 w-8" /></div>}<div className="min-w-0"><h2 className="text-xl font-bold text-gray-900">{app.slug ? <Link href={`/app-store/${encodeURIComponent(app.slug)}`} className="hover:text-blue-700">{name}</Link> : name}</h2><p className="mt-1 text-sm font-semibold text-blue-700">{solutionKindLabel(app.solutionKind)} · {app.category}</p><div className="mt-2 flex flex-wrap gap-2"><Badge>{lifecycleLabel(app.status)}</Badge><Badge subtle>{availabilityLabel(app.availability)}</Badge></div></div></div><p className="mt-5 text-gray-700">{compactSummary(app.description)}</p>{app.features.length > 0 && <ul className="mt-5 space-y-2 text-sm text-gray-600">{app.features.slice(0, 5).map((feature) => <li key={feature} className="flex gap-2"><span aria-hidden="true" className="text-green-600">✓</span><span>{feature}</span></li>)}</ul>}<div className="mt-auto pt-6">{isCommercialProduct(app) && <p className="mb-3 text-sm font-semibold text-gray-800">Commercial terms by enquiry</p>}{cta && (cta.external ? <a href={cta.href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white hover:bg-blue-700">{cta.label}<ExternalLink className="h-4 w-4" /></a> : <Link href={cta.href} className="inline-flex items-center rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white hover:bg-blue-700">{cta.label}</Link>)}</div></article>;
}
function Badge({ children, subtle = false }: { children: React.ReactNode; subtle?: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${subtle ? 'bg-gray-100 text-gray-700' : 'bg-blue-100 text-blue-800'}`}>{children}</span>; }
