'use client';

import Link from 'next/link';
import { Check } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { PriceRange, PricingSettings } from '@/lib/pricing';
import { formatGhsPriceRange, formatUsdPriceRange, ghsConversionAvailable } from '@/lib/pricing';

type Currency = 'USD' | 'GHS';
export default function CurrencyPricing({ pricing }: { pricing: PricingSettings }) {
  const [currency, setCurrency] = useState<Currency>('USD'); const canShowGhs = ghsConversionAvailable(pricing);
  useEffect(() => { const selected = window.sessionStorage.getItem('frontier-pricing-currency'); if (selected === 'GHS' && canShowGhs) setCurrency('GHS'); }, [canShowGhs]);
  const choose = (value: Currency) => { setCurrency(value); window.sessionStorage.setItem('frontier-pricing-currency', value); };
  const display = (price: PriceRange) => currency === 'GHS' ? formatGhsPriceRange(price, pricing) : formatUsdPriceRange(price);
  const effective = new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(pricing.exchangeRateEffectiveAt));
  return <><div className="mb-10 text-center"><div role="group" aria-label="Display currency" className="inline-flex rounded-xl border border-gray-300 bg-white p-1"><CurrencyButton active={currency === 'USD'} onClick={() => choose('USD')}>USD</CurrencyButton><CurrencyButton active={currency === 'GHS'} disabled={!canShowGhs} onClick={() => choose('GHS')}>GHS</CurrencyButton></div><p className="mt-4 text-sm font-bold uppercase tracking-[0.16em] text-blue-700">{currency === 'USD' ? 'Authoritative prices in US dollars (USD)' : 'Approximate prices in Ghana cedis (GHS)'}</p><p className="mt-2 text-sm text-gray-600">USD amounts are authoritative planning estimates. These estimates are subject to a written quotation.</p>{currency === 'GHS' && canShowGhs && <p className="mx-auto mt-3 max-w-2xl text-sm text-gray-600">Approximate conversion: 1 USD = {pricing.exchangeRate.toLocaleString('en', { minimumFractionDigits: 4, maximumFractionDigits: 4 })} GHS · <a href={pricing.exchangeRateSourceUrl} target="_blank" rel="noopener noreferrer" className="font-semibold text-blue-700 underline">{pricing.exchangeRateSourceLabel}</a> · effective {effective} · refreshed automatically from the official source · expires after {pricing.exchangeRateMaxAgeDays} days.</p>}{!canShowGhs && <p className="mx-auto mt-3 max-w-2xl rounded-lg bg-amber-50 p-3 text-sm font-semibold text-amber-900">GHS conversion is temporarily unavailable because the official exchange-rate source could not provide a rate dated within the last seven days. USD estimates remain authoritative and available.</p>}</div><div className="grid gap-7 md:grid-cols-2 xl:grid-cols-4">{pricing.tiers.map((tier) => <article key={tier.id} className="flex flex-col rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-wide text-blue-700">{tier.popular ? 'Popular package' : 'Engagement package'}</p><h2 className="mt-2 text-2xl font-bold text-gray-900">{tier.title}</h2><p className="mt-4 text-3xl font-bold text-gray-950">{display(tier.price)}</p><p className="mt-3 text-gray-600">{tier.description}</p><p className="mt-3 text-sm font-semibold text-gray-700">Typical starting scope: {tier.timeline}</p><ul className="mt-6 space-y-3">{tier.features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-gray-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-green-600" />{feature}</li>)}</ul><Link href="/contact#request-build" className="mt-auto pt-7"><span className="block rounded-lg bg-blue-700 px-4 py-3 text-center font-bold text-white hover:bg-blue-800">Request a quotation</span></Link></article>)}</div><section className="mt-14 grid gap-8 lg:grid-cols-2"><PriceList title="Development services" items={pricing.developmentServices} display={display} /><PriceList title="Additional services" items={pricing.additionalServices} display={display} /></section></>;
}
function CurrencyButton({ active, disabled = false, onClick, children }: { active: boolean; disabled?: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={active} disabled={disabled} onClick={onClick} className={`min-h-11 rounded-lg px-5 py-2 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700 ${active ? 'bg-blue-700 text-white' : 'text-gray-700 hover:bg-gray-100'} disabled:cursor-not-allowed disabled:opacity-50`}>{children}</button>; }
function PriceList({ title, items, display }: { title: string; items: PricingSettings['developmentServices']; display: (price: PriceRange) => string }) { return <div className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-2xl font-bold text-gray-900">{title}</h2><dl className="mt-5 divide-y divide-gray-100">{items.map((item) => <div key={item.id} className="flex items-start justify-between gap-5 py-3"><dt className="text-gray-700">{item.service}</dt><dd className="text-right font-bold text-blue-700">{display(item.price)}</dd></div>)}</dl></div>; }
