'use client';
import {useEffect,useRef,useState} from 'react';
type Summary={activeSessionCount:number;activeSessions:Array<{id:string;page:string;source:string;country:string;city:string}>;recentViews:Array<{page:string;source:string;created_at:string}>;views24h:number;openIncidents:number;unresolvedEnquiries:number;notificationConfigured:boolean;emailConfigured:boolean;whatsappConfigured:boolean;whatsappDeliveries:Array<{event_id:string;status:string;attempts:number;last_error:string|null}>;settings:{visitor_alerts:boolean;summary_enabled:boolean;summary_hour:number};events:Array<{id:string;subject:string;status:string;kind:string;details?:{severity?:string;route?:string;correlationId?:string;sourceHash?:string};resolved_at:string|null;created_at:string}>;locationNotice:string};
export default function MonitoringPanel(){
  const [data,setData]=useState<Summary>(); const [error,setError]=useState('');
  const [testBusy,setTestBusy]=useState(false); const [clearBusy,setClearBusy]=useState(false); const [notice,setNotice]=useState<{ok:boolean;text:string}>(); const testLocked=useRef(false); const approvalCheckLocked=useRef(false);
  const refresh=async()=>{try{const r=await fetch('/api/admin/monitoring',{cache:'no-store'});if(!r.ok)throw Error('Monitoring not configured or unavailable');setData(await r.json());setError('');}catch(e){setError(String(e));}};
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);return()=>clearInterval(timer);},[]);
  const latestTest=data?.events.find(event=>event.kind==='test');
  const latestTestDelivery=data?.whatsappDeliveries.find(item=>item.event_id===latestTest?.id);
  const templatePending=Boolean(latestTestDelivery?.last_error?.includes(' is pending in Meta.'));
  useEffect(()=>{if(!templatePending)return;const check=async()=>{if(document.visibilityState!=='visible'||approvalCheckLocked.current)return;approvalCheckLocked.current=true;try{const r=await fetch('/api/admin/monitoring',{method:'PUT'});const result=await r.json().catch(()=>({}));if(r.ok&&result.whatsapp?.sent)setNotice({ok:true,text:'Meta approved the template and the existing WhatsApp test was submitted. No duplicate test was created.'});await refresh();}finally{approvalCheckLocked.current=false;}};const timer=setInterval(()=>void check(),60000);return()=>clearInterval(timer);},[templatePending]);
  const save=async(settings:Summary['settings'])=>{const r=await fetch('/api/admin/monitoring',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});if(!r.ok)setError('Settings could not be saved');else await refresh();};
  const sendTest=async()=>{if(testLocked.current)return;testLocked.current=true;setTestBusy(true);setNotice(undefined);try{const r=await fetch('/api/admin/monitoring',{method:'POST'});const result=await r.json().catch(()=>({}));if(!r.ok)throw Error(result.error||'Test alert could not be sent');const whatsapp=result.whatsapp;if(whatsapp?.sent)setNotice({ok:true,text:'Test submitted once to email and WhatsApp. Delivery statuses will refresh below.'});else setNotice({ok:false,text:`Email test queued. WhatsApp: ${whatsapp?.error||'not sent.'}`});await refresh();}catch(e){setNotice({ok:false,text:e instanceof Error?e.message:'Test alert could not be sent'});}finally{setTestBusy(false);testLocked.current=false;}};
  const clearObsolete=async()=>{if(clearBusy||!window.confirm('Clear test alerts and stale routine monitoring entries? Customer enquiries and unresolved incidents will be kept.'))return;setClearBusy(true);setNotice(undefined);try{const r=await fetch('/api/admin/monitoring',{method:'DELETE'});const result=await r.json().catch(()=>({}));if(!r.ok)throw Error(result.error||'Obsolete entries could not be cleared');setNotice({ok:true,text:`Cleared ${result.removed||0} obsolete monitoring entr${result.removed===1?'y':'ies'}.`});await refresh();}catch(e){setNotice({ok:false,text:e instanceof Error?e.message:'Obsolete entries could not be cleared'});}finally{setClearBusy(false);}};
  return <section className="mb-8 rounded-xl border border-gray-200 bg-white p-6 text-gray-900 shadow"><h2 className="text-xl font-bold text-gray-950">Monitoring &amp; owner alerts</h2>{error&&<p className="mt-3 font-semibold text-red-700" role="alert">{error}</p>}{data&&<>
    <p className="my-3 font-medium text-gray-800">{data.activeSessionCount} active anonymous sessions · {data.views24h} page views in 24h · {data.openIncidents} open incidents · {data.unresolvedEnquiries} unresolved enquiries</p>
    <p className="text-sm text-gray-600">{data.locationNotice} Only opted-in activity is counted. Refreshes every 15 seconds. Active means seen within 90 seconds.</p>
    <div className="my-4 flex flex-wrap gap-4 font-medium text-gray-800"><label><input type="checkbox" checked={data.settings.visitor_alerts} onChange={e=>void save({...data.settings,visitor_alerts:e.target.checked})}/> Visitor-arrival alerts (maximum 6/hour)</label><label><input type="checkbox" checked={data.settings.summary_enabled} onChange={e=>void save({...data.settings,summary_enabled:e.target.checked})}/> Daily summary</label><label>Summary hour (UTC/Ghana) <select className="rounded border border-gray-400 bg-white px-2 py-1 text-gray-900" value={data.settings.summary_hour} onChange={e=>void save({...data.settings,summary_hour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i}>{i}</option>)}</select></label></div>
    <p className="text-gray-800">Email: {data.emailConfigured?'configured':'not configured'} · WhatsApp: {data.whatsappConfigured?'configured':'awaiting Meta credentials and approved template'}. Enquiries remain saved if either channel fails.</p>
    <button type="button" disabled={testBusy||templatePending} aria-busy={testBusy} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:bg-blue-400" onClick={()=>void sendTest()}>{testBusy?'Sending one test…':templatePending?'Awaiting Meta approval — checking automatically':'Send one labelled test (maximum 2/hour)'}</button>
    {notice&&<p className={`mt-3 rounded-lg border px-4 py-3 font-medium ${notice.ok?'border-green-200 bg-green-50 text-green-800':'border-red-200 bg-red-50 text-red-800'}`} role="status" aria-live="polite">{notice.text}</p>}
    <h3 className="mt-4 font-semibold text-gray-950">Active pages &amp; sources</h3>{data.activeSessions.map(s=><p className="text-gray-800" key={s.id}>{s.page} · {s.source} · {[s.city,s.country].filter(Boolean).join(', ')||'Location unavailable'}</p>)}
    <details className="mt-4 text-gray-800"><summary className="cursor-pointer font-semibold text-gray-950">Recent page views</summary>{data.recentViews.map((v,i)=><p key={i}>{v.created_at} · {v.page} · {v.source}</p>)}</details>
    <details className="mt-4 text-gray-800"><summary className="cursor-pointer font-semibold text-gray-950">Alert delivery, incidents &amp; security audit (latest {Math.min(data.events.length,25)})</summary><button type="button" disabled={clearBusy} className="mt-3 rounded border border-red-300 px-3 py-2 font-semibold text-red-700 disabled:cursor-not-allowed disabled:opacity-60" onClick={()=>void clearObsolete()}>{clearBusy?'Clearing…':'Clear obsolete entries'}</button>{data.events.slice(0,25).map(e=>{const whatsapp=data.whatsappDeliveries.find(item=>item.event_id===e.id);return <div className="mt-2 border-b border-gray-100 pb-2" key={e.id}><p>{e.created_at} · {e.subject} · Email: {e.status} · WhatsApp: {whatsapp?.status||'not queued'}{e.kind==="incident"&&!e.resolved_at&&<button className="ml-3 font-semibold text-blue-700 underline" onClick={()=>{if(window.confirm("Have you verified this incident has recovered?"))void fetch("/api/admin/monitoring",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({resolveId:e.id})}).then(()=>refresh());}}>Confirm recovery</button>}</p>{whatsapp?.last_error&&<p className="text-sm text-red-700">WhatsApp: {whatsapp.last_error}</p>}{e.kind==='security'&&<p className="text-sm text-gray-600">{e.details?.route} · source {e.details?.sourceHash} · correlation {e.details?.correlationId}</p>}</div>})}</details>
  </>}</section>;
}
