import type { Metadata } from 'next';
import Link from 'next/link';
import { Code2, Cpu, ExternalLink, Wrench } from 'lucide-react';
import AppArtwork from '@/components/AppArtwork';
import { listApps } from '@/lib/apps';
import { approvedUpworkUrl, toUpworkSafeProject } from '@/lib/upwork-safe';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Professional Portfolio', description: 'Selected software and engineering work from Frontier DevConsults for Upwork opportunities.', alternates: { canonical: '/upwork-portfolio' }, robots: { index: false, follow: true }, openGraph: { title: 'Professional Portfolio | Frontier DevConsults', description: 'Owner-approved software and engineering evidence for Upwork opportunities.', url: '/upwork-portfolio', images: ['/og-image.png'] }, twitter: { card: 'summary_large_image', title: 'Frontier DevConsults Professional Portfolio', description: 'Selected software and engineering work.', images: ['/og-image.png'] } };

export default async function UpworkPortfolioPage() {
  let projects: NonNullable<ReturnType<typeof toUpworkSafeProject>>[] = [];
  try { projects = (await listApps(false)).map(toUpworkSafeProject).filter((item): item is NonNullable<typeof item> => Boolean(item)); } catch (error) { console.error('Safe portfolio fetch failed:', error); }
  const profile = approvedUpworkUrl();
  return <main id="main-content" className="min-h-screen bg-slate-50">
    <section className="bg-gradient-to-br from-slate-950 to-blue-950 py-20 text-white"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-300">Professional portfolio</p><h1 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">Software engineering, responsible AI integration, and engineering problem-solving.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">Frontier DevConsults is led through hands-on technical work, from planning and architecture through implementation, validation, and delivery. The evidence below appears only when explicitly approved for this portfolio.</p><div className="mt-8 rounded-xl border border-blue-400/30 bg-blue-400/10 p-4 font-semibold text-blue-50">For Upwork opportunities, please continue all pre-contract communication and contracting through Upwork.</div>{profile && <a href={profile} target="_blank" rel="noopener noreferrer" aria-label="Return to Upwork profile (opens in a new tab)" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 font-bold text-blue-900 hover:bg-blue-50">Return to Upwork profile<ExternalLink className="h-4 w-4" aria-hidden="true" /></a>}</div></section>
    <section className="py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-3xl font-bold text-gray-900">Capability areas</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><Pillar icon={<Code2 />} title="Full-stack platforms" text="Responsive web applications, APIs, databases, administrative systems, and cloud delivery." /><Pillar icon={<Cpu />} title="AI applications" text="Model integration, workflow automation, validation, safeguards, and human oversight." /><Pillar icon={<Wrench />} title="Electrical and electronics" text="Circuit and power-electronics analysis, diagnostics, control systems, and technical documentation." /></div></div></section>
    <section className="bg-white py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-3xl font-bold text-gray-900">Selected evidence</h2><p className="mt-2 text-gray-600">Stable, job-relevant case studies approved for pre-contract sharing.</p>{projects.length === 0 ? <div className="mt-8 rounded-xl border border-dashed border-gray-300 p-10 text-center text-gray-600">No case studies are currently approved for this sharing route.</div> : <div className="mt-8 grid gap-6 md:grid-cols-2">{projects.map((project) => <article key={project.slug} className="rounded-2xl border border-gray-200 p-6 shadow-sm"><div className="flex gap-4"><AppArtwork name={project.name} src={project.artwork[0] || null} size="case-study" /><div><h3 className="text-xl font-bold text-gray-900"><Link href={`/upwork-portfolio/${encodeURIComponent(project.slug)}`} className="hover:text-blue-700">{project.name}</Link></h3><p className="mt-1 text-sm font-semibold text-blue-700">{project.kind} · {project.lifecycle}</p></div></div><p className="mt-4 leading-7 text-gray-700">{project.summary}</p>{project.skillTags.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{project.skillTags.slice(0, 6).map((tag) => <span key={tag} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-800">{tag}</span>)}</div>}<Link href={`/upwork-portfolio/${encodeURIComponent(project.slug)}`} className="mt-5 inline-flex font-bold text-blue-700 hover:text-blue-900">View case study →</Link></article>)}</div>}</div></section>
  </main>;
}
function Pillar({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-2xl border border-gray-200 bg-white p-6"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-lg bg-blue-100 text-blue-700">{icon}</div><h3 className="text-lg font-bold text-gray-900">{title}</h3><p className="mt-2 leading-7 text-gray-600">{text}</p></article>; }
