-- Broaden Frontier Engineering OS positioning from electronics-focused to the full
-- Electrical & Electronics Engineering domain while preserving current-vs-roadmap truthfulness.
BEGIN;

UPDATE public.apps
SET
  category = 'Electrical & Electronics Engineering Platform / Instrumentation / AI / PCB & EDA',
  description = 'Frontier Engineering OS is a unified Electrical and Electronics Engineering operating environment that brings professional measurement, instrumentation, diagnostics, data acquisition, engineering intelligence, electrical power analysis, electronics design, PCB/EDA, component engineering, project management, technical documentation and manufacturing workflows into one extensible platform. Its scope spans signal-level electronics, embedded systems and PCB development through electrical machines, generators, transformers, power conversion, solar and energy systems, three-phase systems, industrial plant electrical work, power quality, protection, control and instrumentation. The current software foundation is operational as an installable PWA and simulator-first engineering workspace. Gen-1 physical instrumentation is still in engineering development and has not yet been fabricated, calibrated or certified. Future high-energy and hazardous-live electrical work will use dedicated modular, isolated and independently certified measurement interfaces rather than treating the current low-voltage prototype architecture as field-ready. The original AI PCB Matrix vision continues inside Frontier Engineering OS as Autonomous PCB Design Intelligence R&D, with the long-term objective of progressing from natural-language requirements to engineer-reviewed production-ready PCB and manufacturing outputs.',
  features = ARRAY[
    'Unified Electrical & Electronics Engineering operating environment',
    'Multi-instrument engineering workbench',
    'Digital multimeter interface',
    'Dual-channel oscilloscope interface',
    'Spectrum-analysis workspace',
    '8-channel logic-analyzer interface',
    'Signal generator / arbitrary waveform generator interface',
    'Universal engineering data logger',
    'Desktop multi-instrument layouts with collapsible sidebar',
    'Responsive tablet and mobile workspace behavior',
    'Projects and engineering sessions',
    'Project-scoped instrument workspace layouts',
    'Frontier Intelligence diagnostics framework',
    'Verified engineering knowledge base',
    'Controlled engineering-data provenance',
    'Consent-aware anonymized engineering case datasets',
    'Recursive engineering-AI training architecture for verified cases',
    'Engineering reports and diagnostic/fault dossiers',
    'PCB & EDA workspace',
    'Component subsystem and component records',
    'Engineering calculators',
    'Manufacturing and fabrication package workflow',
    'Provider-neutral manufacturing architecture',
    'Hardware abstraction layer and capability discovery',
    'Device Manager for simulator and future physical modules',
    'Frontier Instrument Protocol control/data architecture',
    'WebUSB physical-device adapter foundation',
    'Installable Progressive Web App',
    'Offline-capable application shell',
    'Gen-1 STM32H743 + ESP32-S3 + Artix-7 hardware architecture',
    'ADS1262 precision measurement architecture',
    'AD9238-65 dual-channel scope architecture',
    'AD9744 waveform-generation architecture',
    'Roadmap for power analyzer and power-quality instrumentation',
    'Roadmap for three-phase, generator, motor and electrical-machine analysis',
    'Roadmap for transformer, protection, switchgear and industrial plant diagnostics',
    'Roadmap for solar PV, battery and energy-storage analysis',
    'Roadmap for isolated high-voltage and current/clamp measurement modules',
    'Roadmap for industrial communications and control/instrumentation diagnostics',
    'AI PCB Matrix integrated as Autonomous PCB Design Intelligence R&D'
  ],
  requirements = ARRAY[
    'Modern desktop, laptop or tablet browser for the current software foundation',
    'PWA-capable browser for installation',
    'Physical Frontier Engineering Instruments hardware required for real measurements when released',
    'Current public preview operates in simulator/foundation mode',
    'Some future cloud, collaboration and AI services may require internet connectivity',
    'Electrical power, plant, machine and hazardous-live measurements require the appropriate future purpose-built measurement modules, probes and certified accessories',
    'Hazardous-live field measurements require independently tested/certified hardware generations and must never be inferred from the present Gen-1 prototype architecture'
  ],
  technologies = ARRAY[
    'React 19',
    'TypeScript 7',
    'Vite 8',
    'Tailwind CSS 4',
    'Motion',
    'Progressive Web App',
    'Hardware Abstraction Layer',
    'Frontier Instrument Protocol',
    'WebUSB integration foundation',
    'GitHub Actions',
    'CMake/GCC firmware reference',
    'SystemVerilog FPGA reference',
    'STM32H743 Gen-1 architecture',
    'ESP32-S3 Gen-1 architecture',
    'AMD Artix-7 XC7A35T Gen-1 architecture',
    'ADS1262 precision ADC architecture',
    'AD9238-65 scope ADC architecture',
    'AD9744 AWG architecture',
    'Modular electrical-power instrumentation roadmap',
    'Isolated high-voltage measurement roadmap',
    'Power-quality and three-phase analysis roadmap'
  ],
  client_problem = 'Electrical and electronics engineering work is fragmented across standalone bench instruments, power analyzers, field meters, data loggers, machine and energy-system tools, separate analysis software, component references, PCB design environments, manufacturing portals and manually assembled reports. This fragmentation duplicates displays and controls, breaks project context between measurement, diagnosis, redesign and maintenance, and prevents verified field and laboratory evidence from accumulating naturally into a reusable engineering knowledge base.',
  solution_summary = 'Frontier Engineering OS consolidates the wider Electrical and Electronics Engineering workflow into one extensible environment. Modular physical instruments provide the measurement, acquisition, generation, isolation and control capabilities appropriate to each domain, while the software supplies visualization, analysis, project context, logging, diagnostics, engineering intelligence, PCB/EDA, manufacturing preparation and reporting. The platform is intended to scale from electronic-circuit work to electrical machines, generators, transformers, solar and storage systems, industrial power, plant electrical systems and future certified high-energy field instrumentation without replacing the core engineering environment.',
  responsibilities = ARRAY[
    'Product and systems architecture',
    'Electrical & Electronics Engineering workflow design',
    'Multi-instrument UI/UX',
    'Hardware abstraction and device architecture',
    'Project/session and engineering-data models',
    'Frontier Intelligence and knowledge-base architecture',
    'Controlled AI-training data provenance',
    'PCB/EDA and manufacturing workflow architecture',
    'Gen-1 instrumentation hardware engineering',
    'Future electrical-power and high-voltage instrumentation roadmap',
    'Future machines, generators, solar, storage and plant diagnostics roadmap',
    'FIP control and acquisition protocol',
    'Reference STM32 firmware and FPGA RTL scaffolding',
    'Safety-generation and certification roadmap',
    'Validation, deployment and release engineering'
  ],
  challenges = ARRAY[
    'Electrical and electronics engineering spans millivolt signal work through high-energy three-phase and DC power systems, so one generic front end cannot safely cover every measurement class.',
    'Precision DC, high-speed oscilloscope, digital logic, RF, impedance, power-quality and hazardous-voltage measurements require different dedicated front ends and protection architectures.',
    'Generators, motors, transformers, solar systems, energy storage and plant electrical systems introduce domain-specific voltage, current, phase, harmonic, protection and machine-state measurements.',
    'Measurement category and safety requirements depend on installation and transient environment, not nominal voltage alone.',
    'Raw high-speed acquisition bandwidth exceeds practical host-link throughput unless FPGA buffering, triggering and decimation are used.',
    'Simulator data must never be confused with physical evidence or used as eligible AI-training evidence.',
    'Calibration state, hardware revision, firmware/RTL versions and data provenance must remain attached to engineering records.',
    'Hazardous-live field instrumentation requires dedicated isolation, protection, probes, spacing and independent certification rather than software limits or larger divider resistors.',
    'Autonomous PCB generation must progressively prove electrical correctness, manufacturability and validation before increasing autonomy.'
  ],
  roadmap_items = ARRAY[
    'Extend the instrument registry beyond electronics-bench instruments into power analyzer, power-quality, three-phase and harmonic-analysis workspaces.',
    'Develop generator, motor, electrical-machine and transformer analysis modules and associated measurement hardware.',
    'Develop solar PV, battery, BMS and energy-storage analysis modules.',
    'Develop protection, switchgear, relay, distribution and industrial plant diagnostic workflows.',
    'Develop isolated high-voltage differential, current/clamp, insulation/leakage and other safety-rated field measurement modules through the Gen-2/Gen-3 certification roadmap.',
    'Add industrial communications and control/instrumentation diagnostics for applicable field systems.',
    'AI PCB Matrix / Autonomous PCB Design Intelligence: progress from natural-language engineering requirements toward production-ready schematic and PCB generation with engineer approval gates.',
    'Automated component selection, constraint reasoning, schematic synthesis, placement, routing and iterative ERC/DRC correction.',
    'Automatic BOM, Gerber, drill, pick-and-place and manufacturing-package generation with provider-neutral handoff.',
    'Fabricate and validate the Gen-1 Frontier Universal Instrument Hub hardware.',
    'Complete native EDA adapters and real manufacturing-provider integrations.',
    'Add dedicated RF, LCR/impedance, automotive and other specialized modules.'
  ],
  technology_stack = jsonb_build_object(
    'Software', jsonb_build_array('React 19','TypeScript 7','Vite 8','Tailwind CSS 4','Motion','Progressive Web App'),
    'Engineering Platform', jsonb_build_array('Hardware Abstraction Layer','Frontier Instrument Protocol','Project/Session Model','Engineering Data Logger','Frontier Intelligence','Verified Engineering Knowledge Base'),
    'Current Gen-1 Hardware Architecture', jsonb_build_array('STM32H743ZI','ESP32-S3','AMD Artix-7 XC7A35T','ADS1262','AD9238-65','AD9744','USB3320','CDCE6214'),
    'Electrical Power Roadmap', jsonb_build_array('Power Analyzer','Power Quality','Three-Phase Analysis','Generators','Electrical Machines','Transformers','Solar PV','Energy Storage','Protection & Plant Diagnostics','Isolated HV & Current Modules'),
    'Validation', jsonb_build_array('Strict TypeScript','Acceptance Tests','GitHub Actions','CMake/GCC Firmware Reference','SystemVerilog/Icarus Reference Simulation','Vivado Release Gates')
  ),
  tagline = 'The All-Inclusive Electrical & Electronics Engineering Workbench — Measure. Analyze. Diagnose. Design. Build.',
  short_description = 'A unified Electrical & Electronics Engineering operating environment combining modular instrumentation, diagnostics, engineering intelligence, electrical-power analysis, PCB/EDA, manufacturing workflows and project documentation in one extensible platform.',
  seo_title = 'Frontier Engineering OS | Electrical & Electronics Engineering Workbench',
  seo_description = 'Frontier Engineering OS unifies electronic instrumentation, electrical power analysis, engineering AI, PCB/EDA, manufacturing workflows, reports and modular hardware for the broader Electrical & Electronics Engineering domain.',
  updated_at = now()
WHERE slug = 'frontier-engineering-os';

UPDATE public.projects
SET
  category = 'Electrical & Electronics Engineering Platform / Instrumentation / AI / PCB & EDA',
  description = 'Frontier Engineering OS is Frontier DevConsults'' unified Electrical and Electronics Engineering workbench: one extensible environment for measurement, diagnostics, multi-instrument operation, electrical power analysis, engineering data, AI-assisted troubleshooting, project records, component intelligence, PCB/EDA workflows, manufacturing preparation and technical reporting. Its intended scope extends from signal-level electronics, embedded systems and PCB development to electrical machines, generators, transformers, power-conversion systems, solar and storage systems, three-phase power, industrial plant electrical systems, power quality, protection, control and instrumentation. The current software foundation is operational as an installable PWA and simulator-first engineering workspace. Gen-1 physical instrumentation is defined but has not yet been fabricated, calibrated or certified. High-energy field capability will be added through dedicated modular and independently certified future hardware rather than by stretching the current low-voltage architecture. The AI PCB Matrix vision remains integrated as Autonomous PCB Design Intelligence R&D.',
  technologies = ARRAY[
    'React 19','TypeScript 7','Vite 8','Tailwind CSS 4','Progressive Web App',
    'Hardware Abstraction Layer','Frontier Instrument Protocol','WebUSB integration foundation',
    'STM32H743 Gen-1 architecture','ESP32-S3 Gen-1 architecture','AMD Artix-7 XC7A35T Gen-1 architecture',
    'ADS1262','AD9238-65','AD9744','GitHub Actions','SystemVerilog reference RTL','CMake/GCC firmware reference',
    'Electrical power instrumentation roadmap','Power-quality and three-phase roadmap','Isolated high-voltage measurement roadmap'
  ],
  features = ARRAY[
    'Unified Electrical & Electronics Engineering operating environment',
    'Multi-instrument engineering workbench',
    'Digital multimeter, oscilloscope, spectrum, logic, AWG and data-logger interfaces',
    'Projects and engineering sessions',
    'Frontier Intelligence diagnostics framework',
    'Verified engineering knowledge base',
    'Controlled recursive AI-training data architecture',
    'PCB & EDA workspace',
    'Component subsystem',
    'Engineering calculators',
    'Manufacturing and fabrication workflow',
    'Engineering reports',
    'Hardware abstraction and capability discovery',
    'Gen-1 modular instrumentation hardware architecture',
    'Roadmap for electrical power, power quality and three-phase analysis',
    'Roadmap for generators, machines, transformers, solar and energy storage',
    'Roadmap for industrial plant, protection and control/instrumentation diagnostics',
    'Roadmap for isolated high-voltage and current measurement modules',
    'Installable PWA',
    'AI PCB Matrix integrated as Autonomous PCB Design Intelligence R&D'
  ],
  updated_at = now()
WHERE slug = 'frontier-engineering-os';

UPDATE public.case_studies
SET
  executive_summary = 'Frontier Engineering OS is a Frontier DevConsults-owned unified Electrical and Electronics Engineering operating environment. It combines multi-instrument measurement interfaces, diagnostics, engineering data acquisition, electrical power and energy-system expansion paths, project/session management, Frontier Intelligence, a verified engineering knowledge base, component and calculator tools, PCB/EDA and manufacturing workflows, engineering reports and a modular hardware architecture in one system. The product is intentionally broader than electronics repair: its target domain includes electronic circuits and embedded systems as well as electrical machines, generators, transformers, solar and storage systems, three-phase power, industrial plant electrical systems, power quality, protection, control and instrumentation. The current software foundation is operational as an installable PWA and simulator-first workbench. Gen-1 physical hardware has been engineered at repository/architecture level but has not yet been fabricated, calibrated or certified. Future high-energy field capability will be provided through purpose-built modular and independently certified measurement hardware. The original AI PCB Matrix vision continues inside Frontier Engineering OS as Autonomous PCB Design Intelligence R&D.',
  intended_market = 'Electrical engineers, electronics engineers, power engineers, instrumentation and control engineers, maintenance and reliability teams, technicians, R&D teams, repair and service engineers, embedded-systems developers, power-electronics engineers, generator and rotating-machine specialists, solar and energy-storage engineers, industrial and plant electrical teams, protection and power-quality specialists, automotive and industrial engineering teams, laboratories, educators, students, product developers and organizations that need an integrated measurement-to-diagnosis-to-design-to-manufacturing engineering environment.',
  problem_opportunity = 'Electrical and electronics engineering workflows are commonly fragmented across standalone bench instruments, field meters, power analyzers, loggers, machine and generator tools, separate analysis programs, disconnected data files, component references, EDA tools, manufacturer portals and manually assembled reports. This duplicates interfaces, loses context between measurement, diagnosis, redesign, maintenance and manufacturing, and prevents verified laboratory and field evidence from naturally accumulating into a reusable engineering knowledge base. Frontier Engineering OS addresses this by treating the broader Electrical and Electronics Engineering workflow as one persistent operating environment.',
  objectives = jsonb_build_array(
    'Create one persistent Electrical & Electronics Engineering environment from measurement and diagnosis through design, manufacture, maintenance and documentation.',
    'Support signal-level electronics and embedded systems while expanding the same platform into electrical power, machines, generators, transformers, energy systems, industrial plant and control/instrumentation workflows.',
    'Replace duplicated standalone instrument interfaces with modular physical instrumentation controlled through a common software workbench.',
    'Allow several engineering instruments to operate side-by-side in one desktop workspace.',
    'Capture engineering data, settings, calibration state, provenance and project context automatically.',
    'Build a controlled verified-case knowledge base suitable for future recursive engineering-AI training across electrical and electronic domains.',
    'Integrate PCB/EDA, component, BOM and manufacturing workflows instead of ending the workflow after diagnosis.',
    'Develop future power, three-phase, machine, generator, solar, storage, protection and plant diagnostic modules without replacing the core software environment.',
    'Preserve the AI PCB Matrix vision as a progressively developed autonomous PCB-design subsystem inside the larger platform.',
    'Maintain explicit safety, calibration and capability boundaries between simulator, prototype, laboratory evaluation and released physical instruments.'
  ),
  challenges_constraints = jsonb_build_array(
    'The target domain spans low-level electronic signals through high-energy electrical power systems, so one generic measurement front end cannot safely or accurately cover every use case.',
    'Precision DC, high-speed oscilloscope, digital logic, RF, impedance, power-quality, three-phase and hazardous-voltage measurements require dedicated front ends and protection architectures.',
    'Generators, motors, transformers, solar systems, energy storage and plant electrical systems introduce domain-specific voltage, current, phase, frequency, harmonic, protection and machine-state requirements.',
    'Measurement category and transient exposure depend on the installation environment, not nominal voltage alone.',
    'Raw high-speed acquisition bandwidth exceeds practical host-link throughput unless FPGA buffering, triggering and decimation are used.',
    'Simulator data must never be confused with physical evidence or used as eligible AI-training evidence.',
    'Calibration state, hardware revision, firmware/RTL versions and data provenance must remain attached to engineering records.',
    'Hazardous-live field instrumentation requires dedicated isolation, protection, probes, spacing and independent certification rather than software limits or larger divider resistors.',
    'Autonomous PCB generation must progressively prove electrical correctness, manufacturability and validation before increasing autonomy.'
  ),
  engineering_approach = 'Frontier separates the system into a universal software environment and modular physical instrumentation. The current application uses a simulator-first hardware abstraction so workflows, logging and diagnostics can be developed without falsely claiming physical performance. Gen-1 focuses on the core electronic instrumentation architecture across STM32H743, ESP32-S3 and Artix-7 with dedicated precision ADC, scope ADC and AWG paths. The same abstraction is intentionally capable of adding future power analyzer, power-quality, three-phase, machine, generator, transformer, solar, storage, protection and plant-oriented modules. High-energy field hardware will remain purpose-built and isolated while the low-voltage mainframe and software environment stay common. The project model connects measurement sessions, component records, PCB/EDA work, manufacturing packages, reports and verified engineering cases. AI functionality is evidence-controlled, and the long-term AI PCB Matrix subsystem remains a staged autonomous design program with engineering review gates.',
  capabilities = jsonb_build_array(
    'Multi-instrument desktop engineering workbench',
    'Collapsible instrument navigation and project-scoped layouts',
    'Digital multimeter interface',
    'Dual-channel oscilloscope interface',
    'Spectrum-analysis workspace',
    '8-channel logic-analyzer interface',
    'Signal generator / AWG interface',
    'Universal engineering data logger',
    'Projects and engineering sessions',
    'Frontier Intelligence live diagnostics framework',
    'Verified engineering knowledge base',
    'Controlled anonymized engineering-case dataset architecture',
    'Engineering reports and diagnostic/fault dossiers',
    'PCB & EDA workspace',
    'Component subsystem',
    'Engineering calculators',
    'Manufacturing/fabrication package workflow',
    'Provider-neutral manufacturing design',
    'Hardware abstraction and capability discovery',
    'Device Manager',
    'Frontier Instrument Protocol',
    'WebUSB physical-device adapter foundation',
    'PWA installation and responsive layouts',
    'Gen-1 modular hardware engineering package',
    'Extensible architecture for future power analyzer, power-quality and three-phase instruments',
    'Extensible architecture for future generator, machine, transformer, solar and storage modules',
    'Extensible architecture for future industrial plant, protection and control/instrumentation diagnostics',
    'High-voltage generation/safety roadmap for future independently certified field modules',
    'AI PCB Matrix Autonomous PCB Design Intelligence roadmap'
  ),
  performance_scalability = 'The application is structured around registries, provider abstractions, projects and modular services so new instruments and hardware generations can be added without replacing the overall engineering environment. This allows the same platform to grow from electronic bench measurements into electrical power, machines, generators, transformers, renewable-energy, plant and industrial instrumentation while keeping specialized hardware domain-specific. FPGA buffering/decimation is part of the high-rate acquisition architecture rather than assuming unlimited host bandwidth. Project-scoped workspaces and controlled engineering records provide the basis for larger datasets and future collaborative/AI services.',
  user_experience = 'The desktop experience is designed as a general engineering workbench rather than a sequence of isolated instrument pages. Multiple instruments can be displayed together, the sidebar collapses into an icon rail to recover workspace width, and mobile/tablet layouts adapt to smaller displays. As the platform expands beyond electronics, the same instrument registry will expose electrical-power, machine, energy and industrial tools when the corresponding hardware and software modules are released. Simulator/foundation labels remain visible so users can distinguish demonstration state from connected physical hardware.',
  technology_architecture = jsonb_build_object(
    'Application', jsonb_build_array('React 19','TypeScript 7','Vite 8','Tailwind CSS 4','Motion','Progressive Web App'),
    'Engineering Core', jsonb_build_array('Hardware Abstraction Layer','Instrument Registry','Project/Session Service','Data Logger','Frontier Intelligence','Verified Knowledge Base','EDA Service','Manufacturing Service'),
    'Physical Interface', jsonb_build_array('Frontier Instrument Protocol','WebUSB Adapter Foundation','STM32H743','ESP32-S3','AMD Artix-7 XC7A35T'),
    'Current Measurement Architecture', jsonb_build_array('ADS1262 Precision ADC','AD9238-65 Dual Scope ADC','AD9744 AWG DAC'),
    'Electrical Power Expansion', jsonb_build_array('Power Analyzer','Power Quality','Three-Phase Analysis','Generators','Electrical Machines','Transformers','Solar PV','Energy Storage','Protection & Plant Diagnostics','Isolated HV & Current Modules'),
    'Reference Validation', jsonb_build_array('Strict TypeScript','Acceptance Tests','GitHub Actions','CMake/GCC Firmware Reference','SystemVerilog/Icarus Reference Simulation','Vivado Release Gates')
  ),
  engineering_insights = 'The central architectural insight is that an engineer should work inside one persistent Electrical & Electronics Engineering environment while measurement hardware, safety classes, AI capability and manufacturing integrations evolve underneath it. The software should remain common whether the engineer is diagnosing a PCB, examining a motor drive, evaluating a generator, studying a three-phase system, analyzing solar/energy-storage equipment or working on an industrial plant electrical problem; only the appropriate purpose-built measurement modules change. The same principle preserves AI PCB Matrix: its goal remains AI-generated production-ready electronics from a textual engineering description, now strengthened by access to measured waveforms, power-system data, diagnosed faults, verified components, project constraints and manufacturing requirements.',
  seo_title = 'Frontier Engineering OS | Electrical & Electronics Engineering Platform Case Study',
  seo_description = 'Frontier DevConsults case study for a unified Electrical & Electronics Engineering OS spanning electronics instrumentation, electrical power and energy-system expansion, engineering AI, PCB/EDA, manufacturing workflows and modular hardware.',
  updated_at = now()
WHERE slug = 'frontier-engineering-os';

COMMIT;
