create table if not exists public.treadmill_licenses (
  id uuid primary key default gen_random_uuid(),
  license_key_hash text not null unique,
  license_key_last4 text not null,
  customer_name text not null,
  license_type text not null check (license_type in ('evaluation','commercial','dealer','site','development')),
  status text not null default 'active' check (status in ('active','suspended','expired','revoked')),
  max_installations integer not null default 1 check (max_installations > 0),
  valid_from timestamptz not null default now(),
  expires_at timestamptz,
  revalidate_days integer not null default 7 check (revalidate_days between 1 and 90),
  offline_grace_days integer not null default 30 check (offline_grace_days between 1 and 365),
  engineering_code_hash text not null,
  signing_key_id text not null default 'ftc-license-v1',
  brand_profile jsonb not null default '{}'::jsonb,
  modules jsonb not null default '["console","media","engineering","white_label"]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.treadmill_license_activations (
  id uuid primary key default gen_random_uuid(),
  license_id uuid not null references public.treadmill_licenses(id) on delete cascade,
  installation_id text not null,
  hardware_device_id text,
  status text not null default 'active' check (status in ('active','deactivated','revoked')),
  first_activated_at timestamptz not null default now(),
  last_validated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  app_version text,
  metadata jsonb not null default '{}'::jsonb,
  unique (license_id, installation_id)
);

create table if not exists public.treadmill_license_events (
  id bigint generated by default as identity primary key,
  license_id uuid references public.treadmill_licenses(id) on delete set null,
  activation_id uuid references public.treadmill_license_activations(id) on delete set null,
  installation_id text,
  event_type text not null,
  success boolean not null default false,
  identity_hash text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.treadmill_engineering_sessions (
  id uuid primary key default gen_random_uuid(),
  license_id uuid not null references public.treadmill_licenses(id) on delete cascade,
  activation_id uuid not null references public.treadmill_license_activations(id) on delete cascade,
  token_hash text not null unique,
  installation_id text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.treadmill_admin_audit (
  id bigint generated by default as identity primary key,
  license_id uuid references public.treadmill_licenses(id) on delete set null,
  activation_id uuid references public.treadmill_license_activations(id) on delete set null,
  actor text not null default 'admin',
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists treadmill_license_activations_license_idx
  on public.treadmill_license_activations(license_id, status);
create index if not exists treadmill_license_events_identity_idx
  on public.treadmill_license_events(identity_hash, event_type, created_at desc);
create index if not exists treadmill_license_events_created_idx
  on public.treadmill_license_events(created_at desc);
create index if not exists treadmill_engineering_sessions_active_idx
  on public.treadmill_engineering_sessions(activation_id, expires_at desc);
create index if not exists treadmill_admin_audit_license_idx
  on public.treadmill_admin_audit(license_id, created_at desc);
create index if not exists treadmill_admin_audit_created_idx
  on public.treadmill_admin_audit(created_at desc);

alter table public.treadmill_licenses enable row level security;
alter table public.treadmill_license_activations enable row level security;
alter table public.treadmill_license_events enable row level security;
alter table public.treadmill_engineering_sessions enable row level security;
alter table public.treadmill_admin_audit enable row level security;

revoke all on public.treadmill_licenses from anon, authenticated;
revoke all on public.treadmill_license_activations from anon, authenticated;
revoke all on public.treadmill_license_events from anon, authenticated;
revoke all on public.treadmill_engineering_sessions from anon, authenticated;
revoke all on public.treadmill_admin_audit from anon, authenticated;

grant select, insert, update, delete on public.treadmill_licenses to service_role;
grant select, insert, update, delete on public.treadmill_license_activations to service_role;
grant select, insert, update, delete on public.treadmill_license_events to service_role;
grant select, insert, update, delete on public.treadmill_engineering_sessions to service_role;
grant select, insert on public.treadmill_admin_audit to service_role;

grant usage, select on sequence public.treadmill_license_events_id_seq to service_role;
grant usage, select on sequence public.treadmill_admin_audit_id_seq to service_role;

create or replace function public.touch_treadmill_license_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists treadmill_licenses_touch_updated_at on public.treadmill_licenses;
create trigger treadmill_licenses_touch_updated_at
before update on public.treadmill_licenses
for each row execute function public.touch_treadmill_license_updated_at();
